name = "canceled-loot-tracker"
main = "src/web/server/index.js"
compatibility_date = "2026-03-15"
compatibility_flags = [ "nodejs_compat" ]

# This maps your worker to the subpath we discussed
[[routes]]
pattern = "www.canceledwow.com/loot*"
zone_name = "canceledwow.com"

[assets]
directory = "./src/web/dist"
binding = "ASSETS"

[build]
command = "npm run build" # Wrangler will run this at the root